// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy5CH3wLytZnLFLnMUnTBG6Y4iBA_uDAU',
    appId: '1:158642198496:web:380544e34f525256623d85',
    messagingSenderId: '158642198496',
    projectId: 'aplikasi-catatan-bee23',
    authDomain: 'aplikasi-catatan-bee23.firebaseapp.com',
    databaseURL: 'https://aplikasi-catatan-bee23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-bee23.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbDQXr68JlkXjhsWCJBtQ7DcaozWwUuY',
    appId: '1:158642198496:android:c4caea6ee6e36130623d85',
    messagingSenderId: '158642198496',
    projectId: 'aplikasi-catatan-bee23',
    databaseURL: 'https://aplikasi-catatan-bee23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-bee23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB96GbgIz-53srSwjdOV3400YbOYycaRVs',
    appId: '1:158642198496:ios:fbbdf93246a8ebf7623d85',
    messagingSenderId: '158642198496',
    projectId: 'aplikasi-catatan-bee23',
    databaseURL: 'https://aplikasi-catatan-bee23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aplikasi-catatan-bee23.appspot.com',
    iosClientId: '158642198496-a33nqoj4s4sfko8mc19jm9p7o8scc78n.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiCatatan',
  );
}
